export const ErrorCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN',
  SESSION_REVOKED: 'SESSION_REVOKED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  PASSWORD_RESET_CONFIGURATION_INVALID: 'PASSWORD_RESET_CONFIGURATION_INVALID',
  EMAIL_CONFIGURATION_INVALID: 'EMAIL_CONFIGURATION_INVALID',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EVALUATOR_NOT_FOUND: 'EVALUATOR_NOT_FOUND',
  INVALID_PRIVILEGED_ROLE: 'INVALID_PRIVILEGED_ROLE',
  EVALUATOR_CATEGORY_ASSIGNMENT_CONFLICT: 'EVALUATOR_CATEGORY_ASSIGNMENT_CONFLICT',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  TEST_SERIES_NOT_FOUND: 'TEST_SERIES_NOT_FOUND',
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_POSITION_CONFLICT: 'QUESTION_POSITION_CONFLICT',
  CATEGORY_NAME_CONFLICT: 'CATEGORY_NAME_CONFLICT',
  MODULE_NAME_CONFLICT: 'MODULE_NAME_CONFLICT',
  PURCHASE_ALREADY_OWNED: 'PURCHASE_ALREADY_OWNED',
  ACTIVE_ENTITLEMENT_EXISTS: 'ACTIVE_ENTITLEMENT_EXISTS',
  PURCHASE_NOT_FOUND: 'PURCHASE_NOT_FOUND',
  TEST_SERIES_NOT_PURCHASABLE: 'TEST_SERIES_NOT_PURCHASABLE',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  INVALID_PAYMENT_SIGNATURE: 'INVALID_PAYMENT_SIGNATURE',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_ORDER_MISMATCH: 'PAYMENT_ORDER_MISMATCH',
  PAYMENT_NOT_CAPTURED: 'PAYMENT_NOT_CAPTURED',
  ENTITLEMENT_NOT_FOUND: 'ENTITLEMENT_NOT_FOUND',
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
  ENTITLEMENT_EXPIRED: 'ENTITLEMENT_EXPIRED',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  TEST_SERIES_UNAVAILABLE: 'TEST_SERIES_UNAVAILABLE',
  TEST_SERIES_NOT_STARTABLE: 'TEST_SERIES_NOT_STARTABLE',
  ATTEMPT_LIMIT_EXCEEDED: 'ATTEMPT_LIMIT_EXCEEDED',
  ATTEMPT_NOT_FOUND: 'ATTEMPT_NOT_FOUND',
  ATTEMPT_EXPIRED: 'ATTEMPT_EXPIRED',
  ATTEMPT_ALREADY_SUBMITTED: 'ATTEMPT_ALREADY_SUBMITTED',
  ATTEMPT_NOT_WRITABLE: 'ATTEMPT_NOT_WRITABLE',
  ATTEMPT_CONTENT_INVALID: 'ATTEMPT_CONTENT_INVALID',
  STALE_ATTEMPT_VERSION: 'STALE_ATTEMPT_VERSION',
  EXAM_SESSION_CONFLICT: 'EXAM_SESSION_CONFLICT',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_NOT_ACCESSIBLE: 'FILE_NOT_ACCESSIBLE',
  FILE_UPLOAD_NOT_ALLOWED: 'FILE_UPLOAD_NOT_ALLOWED',
  FILE_UPLOAD_EXPIRED: 'FILE_UPLOAD_EXPIRED',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_UPLOAD_INCOMPLETE: 'FILE_UPLOAD_INCOMPLETE',
  FILE_ALREADY_FINALIZED: 'FILE_ALREADY_FINALIZED',
  EVALUATION_NOT_FOUND: 'EVALUATION_NOT_FOUND',
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  EVALUATION_ALREADY_EXISTS: 'EVALUATION_ALREADY_EXISTS',
  EVALUATION_INVALID_STATE: 'EVALUATION_INVALID_STATE',
  EVALUATOR_NOT_AUTHORIZED: 'EVALUATOR_NOT_AUTHORIZED',
  EVALUATOR_NOT_ASSIGNED: 'EVALUATOR_NOT_ASSIGNED',
  EVALUATION_NOT_EDITABLE: 'EVALUATION_NOT_EDITABLE',
  EVALUATION_ALREADY_COMPLETED: 'EVALUATION_ALREADY_COMPLETED',
  EVALUATION_ALREADY_FINALIZED: 'EVALUATION_ALREADY_FINALIZED',
  EVALUATION_NOT_READY: 'EVALUATION_NOT_READY',
  REVISION_NOT_FOUND: 'REVISION_NOT_FOUND',
  REVISION_ALREADY_FINALIZED: 'REVISION_ALREADY_FINALIZED',
  UNAUTHORIZED_RE_EVALUATION: 'UNAUTHORIZED_RE_EVALUATION',
  CONCURRENT_REVISION_CONFLICT: 'CONCURRENT_REVISION_CONFLICT',
  INVALID_SCORE: 'INVALID_SCORE',
  INVALID_SUBMISSION_TYPE: 'INVALID_SUBMISSION_TYPE',
  AUTOMATIC_EVALUATION_FAILED: 'AUTOMATIC_EVALUATION_FAILED',
  RESULT_NOT_FOUND: 'RESULT_NOT_FOUND',
  EVALUATION_NOT_FINALIZED: 'EVALUATION_NOT_FINALIZED',
  INVALID_RESULT_STATE: 'INVALID_RESULT_STATE',
  QUESTION_PAPER_NOT_FOUND: 'QUESTION_PAPER_NOT_FOUND',
  QUESTION_PAPER_REQUIRED: 'QUESTION_PAPER_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 'IDEMPOTENCY_REQUEST_IN_PROGRESS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes] | string;

export type AppErrorOptions = {
  message: string;
  statusCode: number;
  code: ErrorCode;
  details?: unknown;
  cause?: unknown;
};

export class AppError extends Error {
  public readonly statusCode: number;
  public readonly code: ErrorCode;
  public readonly details?: unknown;
  public readonly isOperational: boolean;

  constructor(options: AppErrorOptions) {
    super(options.message, options.cause !== undefined ? { cause: options.cause } : undefined);
    this.name = 'AppError';
    this.statusCode = options.statusCode;
    this.code = options.code;
    this.details = options.details;
    this.isOperational = true;
  }
}

export function accountDisabledError(): AppError {
  return new AppError({
    statusCode: 403,
    code: ErrorCodes.ACCOUNT_DISABLED,
    message: 'Account is disabled.',
  });
}
